// This file is auto-generated. Do not edit manually.
import { Project } from "./projects-page-config";

export const projects: Project[] = [
  {
    "id": "project-0001",
    "name": "SmartGuide",
    "case": "avi",
    "whatIsProject": "SmartGuide is a platform that helps teachers gain insights using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "SmartGuide brings AI-powered insights to businesses.",
    "githubUrl": "https://github.com/alphabits/smartguide",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=1"
  },
  {
    "id": "project-0002",
    "name": "HealthHub",
    "case": "avi",
    "whatIsProject": "HealthHub is a platform that helps individuals gain insights using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "HealthHub brings AI-powered insights to developers.",
    "githubUrl": "https://github.com/codecrafters/healthhub",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=2"
  },
  {
    "id": "project-0003",
    "name": "EcoTrack",
    "case": "Trade Republic",
    "whatIsProject": "EcoTrack is a platform that helps teachers gain insights using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "EcoTrack brings AI-powered insights to students.",
    "githubUrl": "https://github.com/quantumleap/ecotrack",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=3"
  },
  {
    "id": "project-0004",
    "name": "TutorAI",
    "case": "avi",
    "whatIsProject": "TutorAI is a platform that helps individuals gain insights using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "TutorAI brings AI-powered insights to developers.",
    "githubUrl": "",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=4"
  },
  {
    "id": "project-0005",
    "name": "RetailRadar",
    "case": "beam",
    "whatIsProject": "RetailRadar is a platform that helps teachers optimize workflows using AI-driven analytics.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "RetailRadar brings AI-powered insights to consumers.",
    "githubUrl": "https://github.com/datadynamos/retailradar",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=5"
  },
  {
    "id": "project-0006",
    "name": "LegalLogic",
    "case": "avi",
    "whatIsProject": "LegalLogic is a platform that helps SMBs optimize workflows using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "LegalLogic brings AI-powered insights to developers.",
    "githubUrl": "https://github.com/neuralnetninjas/legallogic",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=6"
  },
  {
    "id": "project-0007",
    "name": "FarmSense",
    "case": "Trade Republic",
    "whatIsProject": "FarmSense is a platform that helps teachers gain insights using AI-driven analytics.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "FarmSense brings AI-powered insights to consumers.",
    "githubUrl": "https://github.com/tensortitans/farmsense",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=7"
  },
  {
    "id": "project-0008",
    "name": "FitFusion",
    "case": "Trade Republic",
    "whatIsProject": "FitFusion is a platform that helps teachers stay organized using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "FitFusion brings AI-powered insights to developers.",
    "githubUrl": "",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=8"
  },
  {
    "id": "project-0009",
    "name": "CityScope",
    "case": "beam",
    "whatIsProject": "CityScope is a platform that helps enterprises improve productivity using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "CityScope brings AI-powered insights to developers.",
    "githubUrl": "https://github.com/bytebuddies/cityscope",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=9"
  },
  {
    "id": "project-0010",
    "name": "FleetFlow",
    "case": "avi",
    "whatIsProject": "FleetFlow is a platform that helps teachers improve productivity using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and PostgreSQL; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "FleetFlow brings AI-powered insights to consumers.",
    "githubUrl": "https://github.com/innovara/fleetflow",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=10"
  },
  {
    "id": "project-0011",
    "name": "EventEase",
    "case": "beam",
    "whatIsProject": "EventEase is a platform that helps teachers stay organized using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "EventEase brings AI-powered insights to students.",
    "githubUrl": "https://github.com/deltaforce/eventease",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=11"
  },
  {
    "id": "project-0012",
    "name": "MindMate",
    "case": "beam",
    "whatIsProject": "MindMate is a platform that helps individuals improve productivity using AI-driven analytics.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "MindMate brings AI-powered insights to consumers.",
    "githubUrl": "",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=12"
  },
  {
    "id": "project-0013",
    "name": "SkillSync",
    "case": "beam",
    "whatIsProject": "SkillSync is a platform that helps enterprises optimize workflows using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "SkillSync brings AI-powered insights to developers.",
    "githubUrl": "https://github.com/visionaryvibes/skillsync",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=13"
  },
  {
    "id": "project-0014",
    "name": "FoodFetch",
    "case": "avi",
    "whatIsProject": "FoodFetch is a platform that helps enterprises stay organized using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "FoodFetch brings AI-powered insights to consumers.",
    "githubUrl": "https://github.com/futureforge/foodfetch",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=14"
  },
  {
    "id": "project-0015",
    "name": "TravelTrek",
    "case": "Trade Republic",
    "whatIsProject": "TravelTrek is a platform that helps teachers optimize workflows using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "TravelTrek brings AI-powered insights to students.",
    "githubUrl": "https://github.com/aicatalysts/traveltrek",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=15"
  },
  {
    "id": "project-0016",
    "name": "Artify",
    "case": "Trade Republic",
    "whatIsProject": "Artify is a platform that helps enterprises optimize workflows using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "Artify brings AI-powered insights to consumers.",
    "githubUrl": "",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=16"
  },
  {
    "id": "project-0017",
    "name": "BuildBuddy",
    "case": "beam",
    "whatIsProject": "BuildBuddy is a platform that helps individuals optimize workflows using AI-driven analytics.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "BuildBuddy brings AI-powered insights to creators.",
    "githubUrl": "https://github.com/brightbrains/buildbuddy",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=17"
  },
  {
    "id": "project-0018",
    "name": "CivicConnect",
    "case": "Trade Republic",
    "whatIsProject": "CivicConnect is a platform that helps SMBs improve productivity using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "CivicConnect brings AI-powered insights to businesses.",
    "githubUrl": "https://github.com/metamakers/civicconnect",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=18"
  },
  {
    "id": "project-0019",
    "name": "CleanCharge",
    "case": "Trade Republic",
    "whatIsProject": "CleanCharge is a platform that helps SMBs gain insights using AI-driven analytics.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "CleanCharge brings AI-powered insights to businesses.",
    "githubUrl": "https://github.com/deepdivers/cleancharge",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=19"
  },
  {
    "id": "project-0020",
    "name": "DocuDesk",
    "case": "Trade Republic",
    "whatIsProject": "DocuDesk is a platform that helps individuals stay organized using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and PostgreSQL; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "DocuDesk brings AI-powered insights to consumers.",
    "githubUrl": "",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=20"
  },
  {
    "id": "project-0021",
    "name": "EnergyEye",
    "case": "Trade Republic",
    "whatIsProject": "EnergyEye is a platform that helps individuals improve productivity using AI-driven analytics.",
    "howBuilt": "Built with React, Node.js, and PostgreSQL; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "EnergyEye brings AI-powered insights to developers.",
    "githubUrl": "https://github.com/corecreators/energyeye",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=21"
  },
  {
    "id": "project-0022",
    "name": "FinFast",
    "case": "avi",
    "whatIsProject": "FinFast is a platform that helps individuals optimize workflows using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and PostgreSQL; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "FinFast brings AI-powered insights to creators.",
    "githubUrl": "https://github.com/streamline/finfast",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=22"
  },
  {
    "id": "project-0023",
    "name": "GrowGrid",
    "case": "avi",
    "whatIsProject": "GrowGrid is a platform that helps enterprises gain insights using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "GrowGrid brings AI-powered insights to developers.",
    "githubUrl": "https://github.com/skylinetech/growgrid",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=23"
  },
  {
    "id": "project-0024",
    "name": "HireHive",
    "case": "beam",
    "whatIsProject": "HireHive is a platform that helps SMBs stay organized using AI-driven analytics.",
    "howBuilt": "Built with React, Node.js, and PostgreSQL; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "HireHive brings AI-powered insights to consumers.",
    "githubUrl": "",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=24"
  },
  {
    "id": "project-0025",
    "name": "InsightIQ",
    "case": "beam",
    "whatIsProject": "InsightIQ is a platform that helps enterprises optimize workflows using AI-driven analytics.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "InsightIQ brings AI-powered insights to students.",
    "githubUrl": "https://github.com/novanext/insightiq",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=25"
  },
  {
    "id": "project-0026",
    "name": "JoyJournal",
    "case": "avi",
    "whatIsProject": "JoyJournal is a platform that helps teachers gain insights using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and PostgreSQL; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "JoyJournal brings AI-powered insights to consumers.",
    "githubUrl": "https://github.com/prismworks/joyjournal",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=26"
  },
  {
    "id": "project-0027",
    "name": "KlinikAI",
    "case": "beam",
    "whatIsProject": "KlinikAI is a platform that helps individuals stay organized using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "KlinikAI brings AI-powered insights to developers.",
    "githubUrl": "https://github.com/techtrailblazers/klinikai",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=27"
  },
  {
    "id": "project-0028",
    "name": "LearnLink",
    "case": "avi",
    "whatIsProject": "LearnLink is a platform that helps teachers improve productivity using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "LearnLink brings AI-powered insights to students.",
    "githubUrl": "",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=28"
  },
  {
    "id": "project-0029",
    "name": "MarketMaven",
    "case": "beam",
    "whatIsProject": "MarketMaven is a platform that helps teachers improve productivity using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Supabase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "MarketMaven brings AI-powered insights to creators.",
    "githubUrl": "https://github.com/fusionfive/marketmaven",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=29"
  },
  {
    "id": "project-0030",
    "name": "NewsNexus",
    "case": "beam",
    "whatIsProject": "NewsNexus is a platform that helps enterprises stay organized using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and PostgreSQL; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "NewsNexus brings AI-powered insights to consumers.",
    "githubUrl": "https://github.com/orbitops/newsnexus",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=30"
  },
  {
    "id": "project-0031",
    "name": "OptimaOps",
    "case": "beam",
    "whatIsProject": "OptimaOps is a platform that helps teachers stay organized using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and PostgreSQL; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "OptimaOps brings AI-powered insights to creators.",
    "githubUrl": "https://github.com/shiftleft/optimaops",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=31"
  },
  {
    "id": "project-0032",
    "name": "PetPal",
    "case": "avi",
    "whatIsProject": "PetPal is a platform that helps teachers gain insights using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "PetPal brings AI-powered insights to students.",
    "githubUrl": "",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=32"
  },
  {
    "id": "project-0033",
    "name": "QuizQuick",
    "case": "beam",
    "whatIsProject": "QuizQuick is a platform that helps individuals gain insights using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "QuizQuick brings AI-powered insights to creators.",
    "githubUrl": "https://github.com/turbotech/quizquick",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=33"
  },
  {
    "id": "project-0034",
    "name": "RouteRight",
    "case": "avi",
    "whatIsProject": "RouteRight is a platform that helps SMBs gain insights using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "RouteRight brings AI-powered insights to businesses.",
    "githubUrl": "https://github.com/ultrabotics/routeright",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=34"
  },
  {
    "id": "project-0035",
    "name": "ShopSmart",
    "case": "avi",
    "whatIsProject": "ShopSmart is a platform that helps enterprises optimize workflows using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "ShopSmart brings AI-powered insights to developers.",
    "githubUrl": "https://github.com/vertexventures/shopsmart",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=35"
  },
  {
    "id": "project-0036",
    "name": "TaskTrack",
    "case": "beam",
    "whatIsProject": "TaskTrack is a platform that helps individuals optimize workflows using AI-driven automation.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "TaskTrack brings AI-powered insights to businesses.",
    "githubUrl": "",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=36"
  },
  {
    "id": "project-0037",
    "name": "VibeVoice",
    "case": "avi",
    "whatIsProject": "VibeVoice is a platform that helps enterprises improve productivity using AI-driven recommendations.",
    "howBuilt": "Built with React, Node.js, and Firebase; AI via OpenAI & Mistral APIs.",
    "difficulties": "Integrating multiple APIs smoothly and ensuring scalability.",
    "oneSentencePitch": "VibeVoice brings AI-powered insights to consumers.",
    "githubUrl": "https://github.com/zenithzone/vibevoice",
    "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=37"
  }
];
